### ISSUE TITLE
Open associated module

### ISSUE THREAD

**Issue by CanKattwinkel** [pkelleter/angular-cli-quick-switch-plugin#11]
Thanks to this plugin the file tree in Angular projects is mostly closed for me. The only thing I'm currently missing is the ability to open modules.

It might be sufficient to search for a *.module.ts file in the same folder and to switch to the next parent folder in case of failure.

**Comment by pkelleter** [comment]
Thank you for your input. I will consider a solution in this regard in the long run. 

However I do not think that there is a simple solution to that, since the project structure regarding modules can be arbitrary. For example there could be a components/ directory in between (that's how I usually structure my code).

Also I don't know how i could easily switch back from the module, because that switch is not state-less. For one component there is only one module, but for one module there are multiple components (usually).

**Comment by pkelleter** [comment]
due to the fact, that this feature requests breaks the nature of the plugin - plus i do not really see a major benefit in it, since usually you should not browse in the modules in the first place - i will close this issue as a wont-fix
