### ISSUE TITLE
Spec support

### ISSUE THREAD

**Issue by freon27** [pkelleter/angular-cli-quick-switch-plugin#6]
Hi,

Really nice feature. Thanks.

Would it be possible for this to support `.spec.ts` so that I can switch between the CLI generated test file and the component files?

Thanks
Nick

**Comment by pkelleter** [comment]
Hey Nick,

Unfortunately i have to tell you, that the current code base does not support .spec.ts files and probably will not support it in the near future. The problem is, that the spec files break the single premise i take on the files names, which is that they have a single dotted extenstion name. Therefore extensions like .foo.bar can not be supported without rewriting the core logic.
That does not mean that i will never implement this feature, but not in the near future, for sure.

Best,
Patrick

**Comment by freon27** [comment]
Thanks for letting me know :)

 I'm thinking of making a fork so I can implement the functionality I need but I was just wondering, is there any special reason for having that limitation?  Purely for simplicity or am I missing something?

**Comment by pkelleter** [comment]
Well, first of all, i actually don't want that feature to be part of the plugin, until i've implemented a settings option, where you can add/remove extensions as you want (which will take some time probably, because i have no idea how to do that an not too much of spare time unfortunately) - for the simple reason, that i am using that plugin myself as well - and whilst we do have spec files, I don't want them to be switched through since most of the time they are not the files i want to end up with in my daily business :) On the other hand, when those settings are implemented I will not have any problems with adding this feature to the plugin whatsoever :)

Secondly, there actually is a technical reason behind it, but you will figure that out when u have a look at the code, i guess. Taking extensions with a dot into account adds quite some complexity to the algorithm, because you can not determine easily how the last/next file's name has to be (foo.spec.ts would become foo.spec.html, which is not going to exist, and so on)

**Comment by dkocich** [comment]
just a suggestion - I would expect to use ALT+S to switch between all files inside the component folder if any of them exist (html, less, scss, css, spec.ts, ts) because all these can appear in CLI project...

**Comment by freon27** [comment]
I'm going to close this for now.  I agree with @dkocich that I would probably find something that cycles through the files in a directory more useful. Hoping I can find one somewhere.

Thanks :)

**Comment by pkelleter** [comment]
for future reference:
webstorm provides a built-in solution for switching between typescript and test files. the default shortcut for this is `cmd + shift + t`
