### ISSUE TITLE
Support *.less

### ISSUE THREAD

**Issue by xiluo58** [pkelleter/angular-cli-quick-switch-plugin#8]
I am working on a project uses less for styles. Could you please support this filetype?

**Comment by pkelleter** [comment]
Hey xiiluo58,

I will add support for less with the next update, it might take another 1 or 2 weeks until I find the time for that though

**Comment by lippoliv** [comment]
+1

@pkelleter Maybe its the best approach to lookup for angular.json and find `schematics.@schematics/angular:component.styleext`

![grafik](https://user-images.githubusercontent.com/2561859/45344257-82968780-b5a3-11e8-9c91-1c26ef4555fd.png)

That should match all devs needs :)

**Comment by pkelleter** [comment]
I like that idea, @lippoliv - I will take a look at how to implement it when I have some spare time :)

**Comment by pkelleter** [comment]
although i lnitially like your idea @lippoliv I turned it down, due to the fact, that with ng6+ multiple projects can be configured within one angular.json, using multiple different styles.
this makes it too complex to check which style should be toggled.
therefore I will work on hardcoded support for a bunch of common styles used along angular.

**Comment by pkelleter** [comment]
less files will be supported with the next release (currently pending in review at JetBrains)
